### ISSUE TITLE
Apps Redesign

### ISSUE THREAD

**Issue by TanyaEfremova** [gnosis/safe-design#118]
### Overview
Change colours, fonts in the UI accordingly to the new branding. 

### What to do
Changes need to be applied cross-platform on Web, Android and iOS.

**Colours change:**
- [x] Adjust colours in Design System
- [ ] Adjust colours in iOS Kit
- [x] Adjust colours in Android Kit

**Font change:**
Replace the font with DM Sans.
- [ ] Replace font in Design System
- [ ] Replace font in iOS Kit
- [ ] Replace font in Android Kit

Apply all changes in the Master Files for each of the platforms.
